feat(rule-set): Add member access as well as function name
smartive/tslint-config pull request #4
Opened 2018-03-26 12:18 UTC by buehler

Adding the following rules:
- `member-access`: force explicit naming of `public` `private` and `protected`
- `jsx-no-lambda`: allow lambda expressions in JSX
- `function-name`: allow (expecially for default imports) an uppercase function name

2018-03-26 13:06 UTC, mfeltscher requested changes
Please also add documentation to README

2018-03-26 13:21 UTC, buehler commented
This will be a breaking change (due to the `member-access` rule)

2018-03-26 13:22 UTC, buehler commented
I'd suggest the following commit msg:

```
BREAKING CHANGE: This adds `member-access` as a required rule.
This rule forces the user to add `public`, `private` and `protected` modifiers
to their class members. To migrate, install the new version and use the
given visibility members on classes.

```

2018-03-26 13:27 UTC, mfeltscher approved these changes

2018-03-26 13:28 UTC, merged

2018-03-27 05:46 UTC, deniaz commented
`function-name` was breaking as well ¯\_(ツ)_/¯