feat(trailing-comma): use correct trailing comma rule
smartive/tslint-config pull request #6
Opened 2018-06-29 07:38 UTC by buehler

Adhere to the compiler warning of the trailing comma when a rest parameter is used.

Example: https://github.com/smartive/giuseppe/blob/develop/src/core/controller/GiuseppeApiController.ts#L38

2018-07-02 16:09 UTC, mfeltscher requested changes
If you update `tslint-config-airbnb` this becomes a breaking change and should therefore result in a new major version.
See https://www.npmjs.com/package/tslint-config-airbnb#versioning

2018-07-03 06:23 UTC, buehler commented
What becomes a breaking change?

2018-07-03 06:45 UTC, mfeltscher approved these changes

2018-07-03 06:46 UTC, mfeltscher commented
As discussed: New major version - rest is looking, go ahead and merge :shipit:

2018-07-03 06:48 UTC, merged